services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - 3ncount3rData:/data/db
    expose:
      - 27017
    ports:
      - '27017:27017'
  cl3anslat3-api:
    build:
      context: .
      dockerfile: cl3anslat3-api.dockerfile
    restart: always
    volumes:
      - ./data:/data
    ports:
      - '5001:5001'
  3ncount3r-api:
    build:
      context: .
      dockerfile: 3ncount3r-api.dockerfile
    restart: always
    ports:
      - '5002:5002'
  3ncount3r-spa:
    build:
      context: .
      dockerfile: 3ncount3r-spa.dockerfile
    restart: always
    ports:
      - '13132:80'
  shell:
    build:
      context: .
      dockerfile: 3ncount3r-shell.dockerfile
    restart: always
    ports:
      - '13131:80'
volumes:
  3ncount3rData: