name: API CD

on:
  workflow_dispatch:

env:
  LAST_TAG: ''
  LAST_VERSION: ''

jobs:
  build:
    uses: ./.github/workflows/step_build.yml
    with:
      sourcePath: "api"

  tagAndVersion:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag Name
        shell: pwsh
        run: |
          . "./scripts/get-ordinal-number.ps1"

          if ($env:LAST_TAG.IndexOf('-') = -1 || $env:LAST_TAG.IndexOf($env:VERSION_NAME) = -1) { 
            $versionOrdinalNumber = Get-OrdinalNumber(1)
            echo "NEXT_VERSION = '$env:VERSION_NAME, $versionOrdinalNumber Level'" >> $env:GITHUB_ENV
          }

          $env:NEXT_VERSION
