name: API CD

on:
  workflow_dispatch:

env:
  LAST_TAG: ''
  LAST_VERSION: ''

jobs:
  call-workflow:
    uses: ./.github/workflows/step_build.yml
    with:
      sourcePath: "api"

  tagAndVersion:
    needs: [ call-workflow ]
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        shell: pwsh
        run: |
          if ($env:LAST_TAG.IndexOf('-') = -1) { echo 'test' } 
