name: API cl3anslat3 CI

on:
  push:
    branches:
      - 'feat/*'
      - '!main'
    paths:
      - backends/api-cl3anslat3/**

jobs:
  build:
    uses: ./.github/workflows/step_build.yml
    with:
      sourcePath: "backends/api-cl3anslat3"
      artifactName: "api-cl3anslat3"
      tagName: 'cl3anslat3-api'
