name: API CI

on:
  push:
    branches:
      - 'feat/*'
      - '!main'
    paths:
      - backends/api-3ncount3r/**

jobs:
  build:
    uses: ./.github/workflows/step_build.yml
    with:
      sourcePath: "api-3ncount3r"
      artifactName: "api-3ncount3r"
