name: API CI

on:
  push:
    branches:
      - 'feat/*'
      - '!main'
    paths:
      - api/**

jobs:
  build:
    uses: ./.github/workflows/step_build.yml
    with:
      sourcePath: "api"
      artifactName: "api"
