name: Shell CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'feat/*'
      - '!main'
    paths:
      - apps/shell/**

jobs:
  build:
    uses: ./.github/workflows/step_build_nx.yml
    with:
      projectName: 'shell'
      tagName: '3ncount3r-shell'
