name: SPA CI

on:
  push:
    branches:
      - 'feat/*'
      - '!main'
    paths:
      - spa/**

jobs:
  build:
    uses: ./.github/workflows/step_build.yml
    with:
      sourcePath: "spa"
      artifactName: "spa"
