services:
  3ncount3r-api:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=8081
    ports:
      - '8080:8080'
      - '8081:8081'
volumes:
  3ncount3rData:
